# Generated by Django 3.2.9 on 2022-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='avatars/default-user.png', null=True, upload_to='avatars/'),
        ),
    ]
