# Generated by Django 3.2.9 on 2022-06-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='choice',
        ),
        migrations.AddField(
            model_name='player',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
