# Generated by Django 3.2.9 on 2022-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='code',
        ),
        migrations.AddField(
            model_name='player',
            name='choice',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
