# Generated by Django 3.2.9 on 2022-06-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220619_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, related_name='player', to='main.Player'),
        ),
    ]
