# Generated by Django 3.2.9 on 2022-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220619_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='player', to='main.Player'),
        ),
    ]
